# Definitions of traceable obstacles
# Identifier corresponds to Traceable ID set in MoCap

node_rate: 100
delta_t: 0.05
horizon_N: 30
obstacle:
      pose_measured: /Target1/pose                         # subscriber topic name
      state_estimation: /Target1/obstacleStateEstimation   # publisher topic name
      state_prediction: /Target1/obstacleStatePrediction   # publisher topic name